services:
  db:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: "postgres"            
      POSTGRES_PASSWORD: "postgres"      
      POSTGRES_DB: "postgres"           
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    driver: local